### PR TITLE
Update dependencies and generate snapshots when needed.

### PR DESCRIPTION
**Pull request by enahum**
This PR includes: 
* dependencies updates to the latest react-redux as well as other dev dependencies
* Eslint fixes
* Remove rollup (no need to transpile even further)
* Generate snapshots only when results change to allow proper memoization
* Allow the mapQueriesToProps to return Realm.Objects when querying with `objectForPrimaryKey` which does not contain a snapshot unless specified in the model definition.

### CODE REVIEW

**Comment by enahum** [comment]
@lamflam as promised here is the PR to update the library

**Comment by enahum** [comment]
So `super` is no longer working and there is no way to access the selector to run the cleanup, I'm trying to find a way to remove the listeners once the component will unmount

**Comment by enahum** [comment]
ok it should be ready to go

**Comment by lamflam** [comment]
Thanks! I will take a look at this tonight.

**Comment by lamflam** [comment]
Thanks so much for these changes @enahum! I have a few questions after starting to go through:

1. Are the `connectAdvanced`, `Provider`, `Subscribe`, `Context`, etc. exact copies from `react-redux`? If not, can you describe what was changed and why it wasn't possible to import these from `react-redux`? I definitely understand that this may have been necessary, but I actually started this library by doing the exact the same (copying the source from `react-redux`) and then found that it was possible to just import that code and override options instead. If at all possible, I would strongly prefer the second approach to avoid keeping these files up to date manually plus all of the testing that comes along with it. If there are specific issues with this, I'm happy to help look into them too.

2. I originally thought that the snapshotting changes made here would be an issue because it would lead to rendering objects that were technically mutable, however it looks like that is true despite this change according to [the docs](https://realm.io/docs/javascript/2.29.0/api/Realm.Collection.html#snapshot) so I definitely like this idea. Did it make a noticeable performance improvement? Also really nice that it supports single objects now, thanks 😄 

One minor thing, could we track the `changed` state of a query without directly mutating the `query` object (maybe just wrapping the whole thing in another object `{ query, changed }`? It probably won't be an issue, but since `query` is a Realm-owned object I don't want to run the chance of an internal change on their part breaking things here.

3. Regarding removing the rollup config: it definitely simplifies the build, but technically this can be used on Node back to v7 which I'm not sure supports everything here (I have not thoroughly looked into this though and very happy to be proven wrong!)

**Comment by enahum** [comment]
@lamflam ok lets start from the beginning
> 1. Are the connectAdvanced, Provider, Subscribe, Context, etc. exact copies from react-redux?
Context and connectAdvance have changes in them, I think we can keep `Subscription` from react-redux but `Provider` needs the changes in `Context` that is why I ported it.

`Context` is creating a React context with the `realm` value instead of null to avoid conflicts.
 `connectedAdvance` was modified to call the selector cleanup to remove the listeners (I made a comment in the code)

2. You are welcome, the performance improvement is definitely there as you don't need to re-render every component only when changes are really applied and if you memoize with selectors is even better.

> One minor thing, could we track the changed state of a query without directly mutating the query object (maybe just wrapping the whole thing in another object { query, changed }?

Absolutely can do, definitely that is a better option, I'll try and make it so it does not create new objects all the time, hopefully I can find a solution for it.

> 3. Regarding removing the rollup config: it definitely simplifies the build, but technically this can be used on Node back to v7 which I'm not sure supports everything here (I have not thoroughly looked into this though and very happy to be proven wrong!)

I can add it back if you feel strongly about it

**Comment by enahum** [comment]
@lamflam I've added react-redux back but we are only using the `Subscription` and as a dependency the `batch` utils files from it, meaning that I've kept the Provider, connect, connectAdvanced and the Context files.

I've also added rollup back

**Comment by lamflam** [comment]
Thanks @enahum, I will review again today.

**Comment by enahum** [comment]
@lamflam were you able to look at it?

**Comment by lamflam** [comment]
@enahum I've started looking through yes. I'm currently playing around with a way to avoid copying `react-redux` source into this project and just use it like we could previously. I'm not sure it's going to work so if I can't figure it out by the weekend we can just move forward with the copy.

**Comment by lamflam** [comment]
Sorry for super long delay, but this has been merged and released as [v0.0.9](https://www.npmjs.com/package/realm-react-redux).

**Comment by enahum** [comment]
Awesome

**Pull request merged**
