### PR TITLE
Adding support for Realm 2

### PR DESCRIPTION
**Pull request by stigi**
realm-react-redux is great! Thanks for working on it! 🙇‍♂️

Realm currently is at `v2.2.1` so all this PR does is bumping the peer dependency.

Test Plan:
- I ran the test suite (had to add `jest-cli` dev dependency) 
- I also bumped the realm version in the example app and ran it

It would be great to see this merged and a new version being released.

Thanks again!

### CODE REVIEW

**Comment by lamflam** [comment]
Thanks for the PR @stigi! I will try to test this all out this week and get a new release pushed out as long as everything is still working with the latest `Realm` version.

**Comment by stigi** [comment]
The official Realm docs now recommend using 'Realm.open' instead of 'new Realm()' to create a realm. This returns a promise though and will fundamentally change the api. As far as I understand this is mostly done for the case where running Schema migrations might take a while. In that case I would generally recommend opening the realm outside of his lib and passing it via the option, which is already possible.

**Comment by stigi** [comment]
@lamflam Was the issue you were seeing `TypeError: environment.setup is not a function`?
If so upgrading jest to `^22` should help. I'll update my branch and see if Travis agrees.

**Comment by stigi** [comment]
Update: Seems like the issue might have been caused by an earlier commit (edb51cd) which wasn't needed. I cleaned up the PR and Travis is all 💚

**Comment by lamflam** [comment]
Awesome, thanks @stigi! This weekend I should have a chance to verify this fixes the issues I was seeing on my project and as long as all is well I will push a new release.

**Comment by lamflam** [comment]
This is now published to npm in v0.0.7.

**Comment by stigi** [comment]
Thanks @lamflam!

**Pull request merged**
